language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/kyungtaeH/test_travis/master/install.sh)
install:
  - arduino --install-library "Ethernet2"
script:
  - build_platforms axio
notifications:
  email:
    on_success: change
    on_failure: change
